services:
  mtproto-proxy:
    #image: telegrammessenger/proxy:latest
    build:
      context: .
      args:
        IP_EXT: ${IP_EXT:-}
        SECRET: ${SECRET:-ec4dd80983dbf12d6b354cf7bcfe9a48}
        WORKERS: ${WORKERS:-1}
        TZ: ${TZ:-Europe/Moscow}
        MTPROTO_REPO_URL: ${MTPROXY_REPO_URL:-https://github.com/TelegramMessenger/MTProxy}
    container_name: mtproto-proxy
    volumes:
      - ./volumes/config:/data
    restart: unless-stopped
    ports:
      - 8443:8888/udp
      - 8443:8888/tcp
    environment:
      - SECRET
      - WORKERS
      - MTPROTO_REPO_URL
      - TZ
      - IP_EXT
